### ISSUE TITLE
[CI] Updatecli seems flaky 

### ISSUE THREAD

**Issue by moukoublen** [elastic/cloudbeat#2158]
**Describe the bug**
UpdateCLI workflows seem flaky and fail most of the time they run.

We should investigate why and how to improve that.

Optionally, we could consider removing the overlap between UpdateCLI (Golang Mod job) and dependabot.

<img width="1146" alt="Screenshot 2024-04-24 at 3 00 33 PM" src="https://github.com/elastic/cloudbeat/assets/1380039/87d032cd-5348-4212-9615-4b595754e81a">

**Comment by olblak** [comment]
I accidentally saw this issue and couldn't resist having a look.
Looking at this pipeline, https://github.com/elastic/cloudbeat/actions/runs/9058657978/job/24884700647
I noticed a failing pipeline in https://github.com/elastic/cloudbeat/blob/2d3a11e484e76d9b9e525b88c2ba7e9c49a49377/.ci/updatecli/updatecli.d/update-hermit.yml#L40 

The default behavior for the shell plugin is to trigger a target "changed" if something was printed on the console output. In this pipeline the target is always flagged as "changed" which triggers a git commit and report an issue when no file need to be committed

So the target 

```

targets:
  hermit:
    name: 'Update hermit and pre-commit packages'
    scmid: default
    kind: shell
    spec:
      command: .ci/updatecli/scripts/update-hermit.sh
      environments:
        - name: PATH
        - name: HOME
```

could probably be improved to 

```
targets:
  hermit:
    name: 'Update hermit and pre-commit packages'
    scmid: default
    kind: shell
    spec:
      changedif:
        kind: file/checksum
        spec:
          files:
            - "your file to monitor"  
      command: 'bin/hermit install'
      environments:
        - name: PATH
        - name: HOME
```

Note that instead of using "file/checksum" it is also possible to use "exitcode"

with something like 

```
targets:
  hermit:
    name: 'Update hermit and pre-commit packages'
    scmid: default
    kind: shell
    spec:
      changedif:
        kind: exitcode
        spec:
          failure: 1
          success: 0
          warning: 2
      command: 'bin/hermit install'
      environments:
        - name: PATH
        - name: HOME
```

I still behind in terms of documentation and still need to document those feature on the updatecli.io documentation
