### ISSUE TITLE
Cloudbeat - Support EKS data yaml schema

### ISSUE THREAD

**Issue by ofiriro3** [elastic/cloudbeat#234]
**Motivation**
As a developer, I would the cloudbeat to be able to read the new data.yaml provided by the EKS integration.

**In-Depth**
As part of developing the EKS integration, we will need to support the new EKS data.yaml schema.
Currently, the data.yaml will look like the following:
```yaml
activated_rules:
  cis_k8s:
    - cis_1_1_1
    - cis_1_1_2
  cis_eks:
    - cis_3_1_1
    - cis_3_1_2
```

Cloudbeat currently performing a scheme validation that doesn't support the `cis_eks` section.

**Related tasks**
https://github.com/elastic/security-team/issues/4160

**Definition of done**
- Cloudbeat is able to load EKS-related data.yaml
