### ISSUE TITLE
ECR Retrieve AWS resource by region

### ISSUE THREAD

**Issue by ofiriro3** [elastic/cloudbeat#282]
**Motivation**
As a developer, I would like to fetch all relevant repositories to evaluate the EKS CIS 5.1.1 rule.

**In-depth**
All the AWS providers require to specify the region of the requested resources to get them from the provider.
I.E, when trying to retrieve a resource from AWS we need to first understand the region of the resource, and then address the relevant AWS provider. 

In our current implementation, there is only one fetcher that needs to address this problem - the ECR fetcher.
The ECR fetcher collects all the AWS images from pods across the cluster and accesses the AWS ECR provider to evaluate the relevant repositories.

**Definition of done**
- Ecr fetcher bulk repositories per region, and sends them together to the relevant regional ECR

**Comment by ofiriro3** [comment]
@ofiriro3 please edit the ticket as bug

**Comment by JordanSh** [comment]
@ofiriro3 please comment about the verification status of this bug

**Comment by ofiriro3** [comment]
For verifying this bug you need to do the following:

1. Create a private ECR repository in two different regions
2. Push some images to these two repositories.
3. Deploy the two new ECR images on your cluster. 
For example:

``` yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: <image_name>-deployment
  labels:
    app: <image>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <name>
  template:
    metadata:
      labels:
        app: <name>
    spec:
      containers:
      - name: <your_ecr_image_name>
        image: <your_ecr_image>
        env:
        - name: AWS_ACCESS_KEY
          value: <access_key>
        - name: AWS_SECRET_ACCESS_KEY
          value: <aws_secret>
 ```

* You have to add your AWS credentials so the EKS cluster will have access to retrieve the image.
