### ISSUE TITLE
Validate AWS auth options

### ISSUE THREAD

**Issue by oren-zohar** [elastic/cloudbeat#403]
**Motivation**
Need to validate all of the authentication options we have with our integration before going G.A.

**Definition of done**
- [x] `access_key` + `secret`
- [x] `access_key` + `secret` + `session_token`
- [x] `shared_credential_file`
- [x] `shared_credential_file` + `credential_profile_name`
- [x] `role_arn` 
- [ ] ~`role_arn`+ `session_token` (possible?)~
- [x] Properly document (in the integration) all the possible valid ways to configure the integration for AWS, what combinations are possible, what are the differences and when each should be used

**Comment by ofiriro3** [comment]
Hi,

**Comment by olegsu** [comment]
* https://github.com/elastic/cloudbeat/issues/403



Kubernetes integration can be used with the following AWS auth options:
1. Access Key & Secret
2. ARN Role
3. Credentials File

## Access Key & Secret
Get the credentials from `~/.aws/credentials` file.
Copy the `aws_access_key_id` and `aws_secret_access_key` from the profile.
### Session Token
When using a session token it is required to provide a new session token every `duration`.
For example: to generate a session token that lasts for one hour, run `aws sts get-session-token --duration-seconds 3600`.

## ARN Role
To assume a different role, make sure that the target role has a `trusted-entity`
```json
{
    {
        "Effect": "Allow",
        "Principal": {
            "AWS": "arn:aws:iam::{AWS_ACCOUNT}:assumed-role/{AWS_ROLE}/{EC2_INSTANCE}"
        },
        "Action": "sts:AssumeRole",
        "Condition": {}
    }
}
```

## Shared Credentials File
To use a shared credentials file:
1. Make sure the credentials file exists on the file system of the pod
2. In case the file has multiple profiles or the profile is not `default` specify the profile name in the "Credential Profile Name" field.

### Example with Kustomize
1. Go to your Kibna UI `app/fleet/agents` and add a new agent `Add Agent`
2. Download the Kubernetes manifests
3. Copy the `~/.aws/credentials`: `cp ~/.aws/credentials .`
4. Apply the following Kustomization `kubectl apply -k kustomize.yaml`
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  # download the manifests Kibana api/fleet/kubernetes/download
  - elastic-agent-managed-kubernetes.yaml 

# make sure to
# cp ~/.aws/credentials .
secretGenerator:
  - behavior: create
    name: aws-credentials
    files:
      - credentials
patches:
  - path: patches/add-shared-credentials-file.yaml
    target:
      kind: DaemonSet 
  - patch: |-
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: aws-credentials
          secret:
            defaultMode: 420
            secretName: aws-credentials
      - op: add
      path: /spec/template/spec/containers/0/volumeMounts/-
      value:
        name: aws-credentials
        mountPath: /etc/.aws
    target:
      kind: DaemonSet 
      
```
