### ISSUE TITLE
Deploy a real life cluster with CSP

### ISSUE THREAD

**Issue by oren-zohar** [elastic/cloudbeat#459]
As we go forward with our product, we would like to create an environment that will simulate a customer cluster.
I.E we would like to deploy a bigger cluster that will represent the best how our CSPM integration will work in the customer environment.
We believe that this kind of deployment will help in detecting future problems that we haven't detected until today, and will help us solve future issues that customers will encounter.

**DoD**
- [ ] Define what is a real-life cluster - how many EC2s, how many pods, nodes and etc.
- [ ] Manually deploy this environment and monitor it for a while.
- [ ] Save the manifest for this cluster + create an automated deployment file for it (IAC)

**Comment by ofiriro3** [comment]
I am updating the ticket following my discussion with @oren-zohar 

1. It will be a bit hard to define what is a "real-life" cluster. Every company has a different use case and a different architecture. 
In the meanwhile, I'll try to explore and I'll use https://github.com/elastic/security-team/issues/5014#issuecomment-1317987479 as a reference for a cluster.
That being said, using a certain number of nodes/pods won't simulate the requirement either since it won't simulate a real load.

There are a few possibilities here:  

a. Find a design partner with a big cluster that we can use in his environment. 
b. Use it on Elastic production/staging environment -  it raises a few questions: do we need to get permission to it? what will be the effect on the cluster, can it cause a performance degradation in production? 
c. Defining and deploying our own environment on AWS - do we need to ask for permission to deploy such a large environment? what is the policy for deploying big clusters in Elastic? how much load do we want to enable on this cluster?

2. Maybe this task is a bit related to the load test epic we are working on. The real life cluster should be the baseline for some of our load-test tests.

**Comment by ofiriro3** [comment]
Quick update from today's progress:

So I contacted multiple people around Elastic, and they pointed me to the `rnd-hosting` channel in slack.
As it seems no, no further permission is needed for deploying a big cluster on AWS.

I was asked just to follow the tagging guidelines - https://docs.google.com/document/d/1FdkJ5EM1tSAqVRvZvmtDSXbBrzS8f7Bw2vENTFes1ek/edit#heading=h.36dv1gu8gyr7

**Comment by ofiriro3** [comment]
At the on-call sync we decided on executing the following steps:

1. Define the environment.
2. Run a short POC and run the environment on aws-dev account.
3. Create an IAC file the will deploy the same environment.

**Comment by ofiriro3** [comment]
Necessarily tags to the deployment:
Division = The value will be from an allowed list of values which are mentioned [here](https://docs.google.com/document/d/1bjz1jqWEImPUETBQlRUynFhskIkPtqrXq5lRlqZlA84/edit#bookmark=id.iuxr1rddqi5j).
org = The value will be from an allowed list of values which are mentioned [here](https://docs.google.com/document/d/1bjz1jqWEImPUETBQlRUynFhskIkPtqrXq5lRlqZlA84/edit#bookmark=id.81nylvv288zx).
team = The team you are on.
project = The project you are working on.

In our case:
Division - Engineering
org - Security
team - Cloud Security Posture
project - csp project

**Comment by ofiriro3** [comment]
In order to define the regular case, let's start by defining the constraints of our environment. 
According to the [official documentation](https://kubernetes.io/docs/setup/best-practices/cluster-large/), a few considerations should be implied.
- No more than 110 pods per node
- No more than 5000 nodes
- No more than 150000 total pods
- No more than 300000 total containers  

So based on - https://github.com/elastic/security-team/issues/5014.
It suggested to most of the environment has less than 250 pods, so we will start by executing our experiment that way.
I have decided to try out the following setup:
- 3 EC2 machines
- 3 Clusters each
- 30 pods per cluster

The total number of pods should be - 225 pods.

**Comment by ofiriro3** [comment]
I attach some of the deployment files I use - 

Deployment file for the kind clusters
```yaml
# three node (two workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
- role: worker
```

Deployment file for the pods 
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 75
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```

**Comment by ofiriro3** [comment]
I was able to deploy all the relevant machines, but fleet doesn't work on versions 8.6/8.6 SNAPSHOT and 8.6 latest. 
This issue is under investigation by the fleet team.

All the ec2 machines are ready, I'll stop the machine for now and pass the credentials to the next on-call

**Comment by oren-zohar** [comment]
@ofiriro3 try the latest snapshot now, it should work

**Comment by kfirpeled** [comment]
can you explain the rationale for using `kind`? as far as I know it is a tool that emulates a kubernetes cluster, and isn't being used as a production level implementation of k8s clusters

**Comment by CohenIdo** [comment]
3 clusters with 3 nodes each were creating using the following configuration:
```yaml
# a cluster with 1 control-plane nodes and 1 worker
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-multi
nodes:
  - role: control-plane
    image: kindest/node:v1.23.12
    extraMounts:
      - hostPath: ./tests/allure/results
        containerPath: /tmp/data
  - role: worker
    image: kindest/node:v1.23.12
    extraMounts:
      - hostPath: ./tests/allure/results
        containerPath: /tmp/data
  - role: worker
    image: kindest/node:v1.23.12
    extraMounts:
      - hostPath: ./tests/allure/results
        containerPath: /tmp/data
```

On each one of the cluster I deployed @ofiriro3's nginx deployment:
```yaml

I attach some of the deployment files I use -

Deployment file for the kind clusters

# three node (two workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
- role: worker
** Important: Please make sure that you are deploying the cluster with Kubernetes 1.23. For example: kind create cluster --image kindest/node:v1.23.12 --config clusterDeployment.yaml
Deployment file for the pods

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 75
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```

Env details:
link: https://real-life-cluster.kb.us-west2.gcp.elastic-cloud.com:9243/app/f
user: `elastic` password: `SPirCWtoxwCweeriMpq6FpiD`

![image](https://user-images.githubusercontent.com/90558359/207392565-eaaea271-112b-4156-94fe-502d9282356e.png)
