### ISSUE TITLE
Old 8.6 KSPM agent is unhealthy after upgrade of stack to 8.7

### ISSUE THREAD

**Issue by jeniawhite** [elastic/cloudbeat#755]
**Describe the bug**
8.6 stack with KSPM and a running agent don't work after upgrading the stack to 8.7 (the older agent is invalid).
<img width="679" alt="image" src="https://user-images.githubusercontent.com/12246907/219428305-92ee0a2a-8b80-42e4-9669-4851b1a92be9.png">

**To Reproduce**
Write the exact actions one should perform in order to reproduce the bug.
1. Deploy 8.6
2. Deploy KSPM with an agent on a kind cluster
3. Upgrade stack to 8.7
4. Go to the fleet and see that agent is unhealthy

**Expected behavior**
Older agents should keep working after the upgrade

**Comment by jeniawhite** [comment]
Investigating the problem I've noticed that this behavior only happens on upgrades.
Deploying a new KSPM policy results in the following policy:
```
inputs:
  - id: logfile-system-76d9c822-44cf-4fcd-acbd-944d6d4c75b9
    name: system-2
    revision: 1
    type: logfile
    use_output: default
    meta:
      package:
        name: system
        version: 1.24.1
    data_stream:
      namespace: default
    package_policy_id: 76d9c822-44cf-4fcd-acbd-944d6d4c75b9
    streams:
      - id: logfile-system.syslog-76d9c822-44cf-4fcd-acbd-944d6d4c75b9
        data_stream:
          dataset: system.syslog
          type: logs
        paths:
          - /var/log/messages*
          - /var/log/syslog*
        exclude_files:
          - .gz$
        multiline:
          pattern: ^\s
          match: after
        processors:
          - add_locale: null
        ignore_older: 72h
      - id: logfile-system.auth-76d9c822-44cf-4fcd-acbd-944d6d4c75b9
        data_stream:
          dataset: system.auth
          type: logs
        ignore_older: 72h
        paths:
          - /var/log/auth.log*
          - /var/log/secure*
        exclude_files:
          - .gz$
        multiline:
          pattern: ^\s
          match: after
        tags:
          - system-auth
        processors:
          - add_locale: null
  - id: winlog-system-76d9c822-44cf-4fcd-acbd-944d6d4c75b9
    name: system-2
    revision: 1
    type: winlog
    use_output: default
    meta:
      package:
        name: system
        version: 1.24.1
    data_stream:
      namespace: default
    package_policy_id: 76d9c822-44cf-4fcd-acbd-944d6d4c75b9
    streams:
      - id: winlog-system.security-76d9c822-44cf-4fcd-acbd-944d6d4c75b9
        name: Security
        data_stream:
          dataset: system.security
          type: logs
        condition: '${host.platform} == ''windows'''
        ignore_older: 72h
      - id: winlog-system.application-76d9c822-44cf-4fcd-acbd-944d6d4c75b9
        name: Application
        data_stream:
          dataset: system.application
          type: logs
        condition: '${host.platform} == ''windows'''
        ignore_older: 72h
      - id: winlog-system.system-76d9c822-44cf-4fcd-acbd-944d6d4c75b9
        name: System
        data_stream:
          dataset: system.system
          type: logs
        condition: '${host.platform} == ''windows'''
        ignore_older: 72h
  - id: system/metrics-system-76d9c822-44cf-4fcd-acbd-944d6d4c75b9
    name: system-2
    revision: 1
    type: system/metrics
    use_output: default
    meta:
      package:
        name: system
        version: 1.24.1
    data_stream:
      namespace: default
    package_policy_id: 76d9c822-44cf-4fcd-acbd-944d6d4c75b9
    streams:
      - id: system/metrics-system.cpu-76d9c822-44cf-4fcd-acbd-944d6d4c75b9
        data_stream:
          dataset: system.cpu
          type: metrics
        metricsets:
          - cpu
        cpu.metrics:
          - percentages
          - normalized_percentages
        period: 10s
      - id: >-
          system/metrics-system.socket_summary-76d9c822-44cf-4fcd-acbd-944d6d4c75b9
        data_stream:
          dataset: system.socket_summary
          type: metrics
        metricsets:
          - socket_summary
        period: 10s
      - id: system/metrics-system.filesystem-76d9c822-44cf-4fcd-acbd-944d6d4c75b9
        data_stream:
          dataset: system.filesystem
          type: metrics
        metricsets:
          - filesystem
        period: 1m
        processors:
          - drop_event.when.regexp:
              system.filesystem.mount_point: ^/(sys|cgroup|proc|dev|etc|host|lib|snap)($|/)
      - id: system/metrics-system.memory-76d9c822-44cf-4fcd-acbd-944d6d4c75b9
        data_stream:
          dataset: system.memory
          type: metrics
        metricsets:
          - memory
        period: 10s
      - id: >-
          system/metrics-system.process.summary-76d9c822-44cf-4fcd-acbd-944d6d4c75b9
        data_stream:
          dataset: system.process.summary
          type: metrics
        metricsets:
          - process_summary
        period: 10s
      - id: system/metrics-system.fsstat-76d9c822-44cf-4fcd-acbd-944d6d4c75b9
        data_stream:
          dataset: system.fsstat
          type: metrics
        metricsets:
          - fsstat
        period: 1m
        processors:
          - drop_event.when.regexp:
              system.fsstat.mount_point: ^/(sys|cgroup|proc|dev|etc|host|lib|snap)($|/)
      - id: system/metrics-system.load-76d9c822-44cf-4fcd-acbd-944d6d4c75b9
        data_stream:
          dataset: system.load
          type: metrics
        metricsets:
          - load
        condition: '${host.platform} != ''windows'''
        period: 10s
      - id: system/metrics-system.diskio-76d9c822-44cf-4fcd-acbd-944d6d4c75b9
        data_stream:
          dataset: system.diskio
          type: metrics
        metricsets:
          - diskio
        diskio.include_devices: null
        period: 10s
      - id: system/metrics-system.process-76d9c822-44cf-4fcd-acbd-944d6d4c75b9
        data_stream:
          dataset: system.process
          type: metrics
        metricsets:
          - process
        period: 10s
        process.include_top_n.by_cpu: 5
        process.include_top_n.by_memory: 5
        process.cmdline.cache.enabled: true
        process.cgroups.enabled: false
        process.include_cpu_ticks: false
        processes:
          - .*
      - id: system/metrics-system.uptime-76d9c822-44cf-4fcd-acbd-944d6d4c75b9
        data_stream:
          dataset: system.uptime
          type: metrics
        metricsets:
          - uptime
        period: 10s
      - id: system/metrics-system.network-76d9c822-44cf-4fcd-acbd-944d6d4c75b9
        data_stream:
          dataset: system.network
          type: metrics
        metricsets:
          - network
        period: 10s
        network.interfaces: null
  - id: aeb2c343-b365-4475-9061-1023487799f9
    name: KSPMPolicy
    revision: 1
    type: cloudbeat/cis_k8s
    use_output: default
    meta:
      package:
        name: cloud_security_posture
        version: 1.2.11
    data_stream:
      namespace: default
    package_policy_id: aeb2c343-b365-4475-9061-1023487799f9
    streams:
      - id: >-
          cloudbeat/cis_k8s-cloud_security_posture.findings-aeb2c343-b365-4475-9061-1023487799f9
        data_stream:
          dataset: cloud_security_posture.findings
          type: logs
        config:
          v1:
            posture: kspm
            deployment: cloudbeat/cis_k8s
            benchmark: cis_k8s
        fetchers:
          - name: kube-api
          - name: process
            directory: /hostfs
            processes:
              etcd: null
              kube-apiserver: null
              kube-controller: null
              kube-scheduler: null
              kubelet:
                config-file-arguments:
                  - config
          - name: file-system
            patterns:
              - /hostfs/etc/kubernetes/scheduler.conf
              - /hostfs/etc/kubernetes/controller-manager.conf
              - /hostfs/etc/kubernetes/admin.conf
              - /hostfs/etc/kubernetes/kubelet.conf
              - /hostfs/etc/kubernetes/manifests/etcd.yaml
              - /hostfs/etc/kubernetes/manifests/kube-apiserver.yaml
              - /hostfs/etc/kubernetes/manifests/kube-controller-manager.yaml
              - /hostfs/etc/kubernetes/manifests/kube-scheduler.yaml
              - /hostfs/etc/systemd/system/kubelet.service.d/10-kubeadm.conf
              - /hostfs/etc/kubernetes/pki/*
              - /hostfs/var/lib/kubelet/config.yaml
              - /hostfs/var/lib/etcd
              - /hostfs/etc/kubernetes/pki
        processors:
          - add_cluster_id: null
        runtime_cfg:
          activated_rules:
            cis_k8s:
              - cis_1_1_1
              - cis_1_1_2
              - cis_1_1_3
              - cis_1_1_4
              - cis_1_1_5
              - cis_1_1_6
              - cis_1_1_7
              - cis_1_1_8
              - cis_1_1_11
              - cis_1_1_12
              - cis_1_1_13
              - cis_1_1_14
              - cis_1_1_15
              - cis_1_1_16
              - cis_1_1_17
              - cis_1_1_18
              - cis_1_1_19
              - cis_1_1_20
              - cis_1_1_21
              - cis_1_2_2
              - cis_1_2_4
              - cis_1_2_5
              - cis_1_2_6
              - cis_1_2_7
              - cis_1_2_8
              - cis_1_2_9
              - cis_1_2_10
              - cis_1_2_11
              - cis_1_2_12
              - cis_1_2_13
              - cis_1_2_14
              - cis_1_2_15
              - cis_1_2_16
              - cis_1_2_17
              - cis_1_2_18
              - cis_1_2_19
              - cis_1_2_20
              - cis_1_2_21
              - cis_1_2_22
              - cis_1_2_23
              - cis_1_2_24
              - cis_1_2_25
              - cis_1_2_26
              - cis_1_2_27
              - cis_1_2_28
              - cis_1_2_29
              - cis_1_2_32
              - cis_1_3_2
              - cis_1_3_3
              - cis_1_3_4
              - cis_1_3_5
              - cis_1_3_6
              - cis_1_3_7
              - cis_1_4_1
              - cis_1_4_2
              - cis_2_1
              - cis_2_2
              - cis_2_3
              - cis_2_4
              - cis_2_5
              - cis_2_6
              - cis_4_1_1
              - cis_4_1_2
              - cis_4_1_5
              - cis_4_1_6
              - cis_4_1_9
              - cis_4_1_10
              - cis_4_2_1
              - cis_4_2_2
              - cis_4_2_3
              - cis_4_2_4
              - cis_4_2_5
              - cis_4_2_6
              - cis_4_2_7
              - cis_4_2_8
              - cis_4_2_9
              - cis_4_2_10
              - cis_4_2_11
              - cis_4_2_12
              - cis_4_2_13
              - cis_5_1_3
              - cis_5_1_5
              - cis_5_1_6
              - cis_5_2_2
              - cis_5_2_3
              - cis_5_2_4
              - cis_5_2_5
              - cis_5_2_6
              - cis_5_2_7
              - cis_5_2_8
              - cis_5_2_9
              - cis_5_2_10
```
As you can see there is a single ID for our integration's input:
```
  - id: aeb2c343-b365-4475-9061-1023487799f9
    name: KSPMPolicy
```
Yet when I look at the policy that got upgraded from `8.6` I can see that it has multiple inputs with the same id likewise:
```
inputs:
  - id: logfile-system-21bb9f22-f89a-467c-b6a7-409bb076474b
    name: system-1
    revision: 1
    type: logfile
    use_output: default
    meta:
      package:
        name: system
        version: 1.24.1
    data_stream:
      namespace: default
    package_policy_id: 21bb9f22-f89a-467c-b6a7-409bb076474b
    streams:
      - id: logfile-system.auth-21bb9f22-f89a-467c-b6a7-409bb076474b
        data_stream:
          dataset: system.auth
          type: logs
        ignore_older: 72h
        paths:
          - /var/log/auth.log*
          - /var/log/secure*
        exclude_files:
          - .gz$
        multiline:
          pattern: ^\s
          match: after
        tags:
          - system-auth
        processors:
          - add_locale: null
      - id: logfile-system.syslog-21bb9f22-f89a-467c-b6a7-409bb076474b
        data_stream:
          dataset: system.syslog
          type: logs
        paths:
          - /var/log/messages*
          - /var/log/syslog*
        exclude_files:
          - .gz$
        multiline:
          pattern: ^\s
          match: after
        processors:
          - add_locale: null
        ignore_older: 72h
  - id: winlog-system-21bb9f22-f89a-467c-b6a7-409bb076474b
    name: system-1
    revision: 1
    type: winlog
    use_output: default
    meta:
      package:
        name: system
        version: 1.24.1
    data_stream:
      namespace: default
    package_policy_id: 21bb9f22-f89a-467c-b6a7-409bb076474b
    streams:
      - id: winlog-system.application-21bb9f22-f89a-467c-b6a7-409bb076474b
        name: Application
        data_stream:
          dataset: system.application
          type: logs
        condition: '${host.platform} == ''windows'''
        ignore_older: 72h
      - id: winlog-system.security-21bb9f22-f89a-467c-b6a7-409bb076474b
        name: Security
        data_stream:
          dataset: system.security
          type: logs
        condition: '${host.platform} == ''windows'''
        ignore_older: 72h
      - id: winlog-system.system-21bb9f22-f89a-467c-b6a7-409bb076474b
        name: System
        data_stream:
          dataset: system.system
          type: logs
        condition: '${host.platform} == ''windows'''
        ignore_older: 72h
  - id: system/metrics-system-21bb9f22-f89a-467c-b6a7-409bb076474b
    name: system-1
    revision: 1
    type: system/metrics
    use_output: default
    meta:
      package:
        name: system
        version: 1.24.1
    data_stream:
      namespace: default
    package_policy_id: 21bb9f22-f89a-467c-b6a7-409bb076474b
    streams:
      - id: system/metrics-system.cpu-21bb9f22-f89a-467c-b6a7-409bb076474b
        data_stream:
          dataset: system.cpu
          type: metrics
        metricsets:
          - cpu
        cpu.metrics:
          - percentages
          - normalized_percentages
        period: 10s
      - id: system/metrics-system.diskio-21bb9f22-f89a-467c-b6a7-409bb076474b
        data_stream:
          dataset: system.diskio
          type: metrics
        metricsets:
          - diskio
        diskio.include_devices: null
        period: 10s
      - id: system/metrics-system.filesystem-21bb9f22-f89a-467c-b6a7-409bb076474b
        data_stream:
          dataset: system.filesystem
          type: metrics
        metricsets:
          - filesystem
        period: 1m
        processors:
          - drop_event.when.regexp:
              system.filesystem.mount_point: ^/(sys|cgroup|proc|dev|etc|host|lib|snap)($|/)
      - id: system/metrics-system.fsstat-21bb9f22-f89a-467c-b6a7-409bb076474b
        data_stream:
          dataset: system.fsstat
          type: metrics
        metricsets:
          - fsstat
        period: 1m
        processors:
          - drop_event.when.regexp:
              system.fsstat.mount_point: ^/(sys|cgroup|proc|dev|etc|host|lib|snap)($|/)
      - id: system/metrics-system.load-21bb9f22-f89a-467c-b6a7-409bb076474b
        data_stream:
          dataset: system.load
          type: metrics
        metricsets:
          - load
        condition: '${host.platform} != ''windows'''
        period: 10s
      - id: system/metrics-system.memory-21bb9f22-f89a-467c-b6a7-409bb076474b
        data_stream:
          dataset: system.memory
          type: metrics
        metricsets:
          - memory
        period: 10s
      - id: system/metrics-system.network-21bb9f22-f89a-467c-b6a7-409bb076474b
        data_stream:
          dataset: system.network
          type: metrics
        metricsets:
          - network
        period: 10s
        network.interfaces: null
      - id: system/metrics-system.process-21bb9f22-f89a-467c-b6a7-409bb076474b
        data_stream:
          dataset: system.process
          type: metrics
        metricsets:
          - process
        period: 10s
        process.include_top_n.by_cpu: 5
        process.include_top_n.by_memory: 5
        process.cmdline.cache.enabled: true
        process.cgroups.enabled: false
        process.include_cpu_ticks: false
        processes:
          - .*
      - id: >-
          system/metrics-system.process.summary-21bb9f22-f89a-467c-b6a7-409bb076474b
        data_stream:
          dataset: system.process.summary
          type: metrics
        metricsets:
          - process_summary
        period: 10s
      - id: >-
          system/metrics-system.socket_summary-21bb9f22-f89a-467c-b6a7-409bb076474b
        data_stream:
          dataset: system.socket_summary
          type: metrics
        metricsets:
          - socket_summary
        period: 10s
      - id: system/metrics-system.uptime-21bb9f22-f89a-467c-b6a7-409bb076474b
        data_stream:
          dataset: system.uptime
          type: metrics
        metricsets:
          - uptime
        period: 10s
  - id: 3b0b8cb0-7531-47e9-8d77-031f9d7c18d8
    name: LocalKind
    revision: 3
    type: cloudbeat/cis_k8s
    use_output: default
    meta:
      package:
        name: cloud_security_posture
        version: 1.2.11
    data_stream:
      namespace: default
    package_policy_id: 3b0b8cb0-7531-47e9-8d77-031f9d7c18d8
    streams:
      - id: >-
          cloudbeat/cis_k8s-cloud_security_posture.findings-3b0b8cb0-7531-47e9-8d77-031f9d7c18d8
        data_stream:
          dataset: cloud_security_posture.findings
          type: logs
        processors:
          - add_cluster_id: null
        config:
          v1:
            posture: null
            benchmark: cis_k8s
            deployment: null
        fetchers:
          - name: kube-api
          - name: process
            processes:
              kube-apiserver: null
              kubelet:
                config-file-arguments:
                  - config
              kube-scheduler: null
              etcd: null
              kube-controller: null
            directory: /hostfs
          - name: file-system
            patterns:
              - /hostfs/etc/kubernetes/scheduler.conf
              - /hostfs/etc/kubernetes/controller-manager.conf
              - /hostfs/etc/kubernetes/admin.conf
              - /hostfs/etc/kubernetes/kubelet.conf
              - /hostfs/etc/kubernetes/manifests/etcd.yaml
              - /hostfs/etc/kubernetes/manifests/kube-apiserver.yaml
              - /hostfs/etc/kubernetes/manifests/kube-controller-manager.yaml
              - /hostfs/etc/kubernetes/manifests/kube-scheduler.yaml
              - /hostfs/etc/systemd/system/kubelet.service.d/10-kubeadm.conf
              - /hostfs/etc/kubernetes/pki/*
              - /hostfs/var/lib/kubelet/config.yaml
              - /hostfs/var/lib/etcd
              - /hostfs/etc/kubernetes/pki
        runtime_cfg:
          activated_rules:
            cis_k8s:
              - cis_1_1_1
              - cis_1_1_2
              - cis_1_1_3
              - cis_1_1_4
              - cis_1_1_5
              - cis_1_1_6
              - cis_1_1_7
              - cis_1_1_8
              - cis_1_1_11
              - cis_1_1_12
              - cis_1_1_13
              - cis_1_1_14
              - cis_1_1_15
              - cis_1_1_16
              - cis_1_1_17
              - cis_1_1_18
              - cis_1_1_19
              - cis_1_1_20
              - cis_1_1_21
              - cis_1_2_2
              - cis_1_2_4
              - cis_1_2_5
              - cis_1_2_6
              - cis_1_2_7
              - cis_1_2_8
              - cis_1_2_9
              - cis_1_2_10
              - cis_1_2_11
              - cis_1_2_12
              - cis_1_2_13
              - cis_1_2_14
              - cis_1_2_15
              - cis_1_2_16
              - cis_1_2_17
              - cis_1_2_18
              - cis_1_2_19
              - cis_1_2_20
              - cis_1_2_21
              - cis_1_2_22
              - cis_1_2_23
              - cis_1_2_24
              - cis_1_2_25
              - cis_1_2_26
              - cis_1_2_27
              - cis_1_2_28
              - cis_1_2_29
              - cis_1_2_32
              - cis_1_3_2
              - cis_1_3_3
              - cis_1_3_4
              - cis_1_3_5
              - cis_1_3_6
              - cis_1_3_7
              - cis_1_4_1
              - cis_1_4_2
              - cis_2_1
              - cis_2_2
              - cis_2_3
              - cis_2_4
              - cis_2_5
              - cis_2_6
              - cis_4_1_1
              - cis_4_1_2
              - cis_4_1_5
              - cis_4_1_6
              - cis_4_1_9
              - cis_4_1_10
              - cis_4_2_1
              - cis_4_2_2
              - cis_4_2_3
              - cis_4_2_4
              - cis_4_2_5
              - cis_4_2_6
              - cis_4_2_7
              - cis_4_2_8
              - cis_4_2_9
              - cis_4_2_10
              - cis_4_2_11
              - cis_4_2_12
              - cis_4_2_13
              - cis_5_1_3
              - cis_5_1_5
              - cis_5_1_6
              - cis_5_2_2
              - cis_5_2_3
              - cis_5_2_4
              - cis_5_2_5
              - cis_5_2_6
              - cis_5_2_7
              - cis_5_2_8
              - cis_5_2_9
              - cis_5_2_10
  - id: 3b0b8cb0-7531-47e9-8d77-031f9d7c18d8
    name: LocalKind
    revision: 3
    type: cloudbeat/cis_aws
    use_output: default
    meta:
      package:
        name: cloud_security_posture
        version: 1.2.11
    data_stream:
      namespace: default
    package_policy_id: 3b0b8cb0-7531-47e9-8d77-031f9d7c18d8
    streams:
      - id: >-
          cloudbeat/cis_aws-cloud_security_posture.findings-3b0b8cb0-7531-47e9-8d77-031f9d7c18d8
        data_stream:
          dataset: cloud_security_posture.findings
          type: logs
        config:
          v1:
            posture: null
            aws:
              credentials:
                type: null
            benchmark: cis_aws
            deployment: null
        fetchers:
          - name: aws-iam
          - name: aws-ec2-network
          - name: aws-s3
          - name: aws-trail
          - name: aws-monitoring
          - name: aws-rds
  - id: 3b0b8cb0-7531-47e9-8d77-031f9d7c18d8
    name: LocalKind
    revision: 3
    type: cloudbeat/cis_gcp
    use_output: default
    meta:
      package:
        name: cloud_security_posture
        version: 1.2.11
    data_stream:
      namespace: default
    package_policy_id: 3b0b8cb0-7531-47e9-8d77-031f9d7c18d8
    streams:
      - id: >-
          cloudbeat/cis_gcp-cloud_security_posture.findings-3b0b8cb0-7531-47e9-8d77-031f9d7c18d8
        data_stream:
          dataset: cloud_security_posture.findings
          type: logs
        config:
          v1:
            posture: null
            benchmark: cis_gcp
            deployment: null
        fetchers: null
  - id: 3b0b8cb0-7531-47e9-8d77-031f9d7c18d8
    name: LocalKind
    revision: 3
    type: cloudbeat/cis_azure
    use_output: default
    meta:
      package:
        name: cloud_security_posture
        version: 1.2.11
    data_stream:
      namespace: default
    package_policy_id: 3b0b8cb0-7531-47e9-8d77-031f9d7c18d8
    streams:
      - id: >-
          cloudbeat/cis_azure-cloud_security_posture.findings-3b0b8cb0-7531-47e9-8d77-031f9d7c18d8
        data_stream:
          dataset: cloud_security_posture.findings
          type: logs
        config:
          v1:
            posture: null
            benchmark: cis_azure
            deployment: null
        fetchers: null
```
Notice that there are 3 `ids` with the same values `3b0b8cb0-7531-47e9-8d77-031f9d7c18d8`.
This is problematic because the input is not unique and the `elastic-agent` components system doesn't allow such a thing, which doesn't trigger `cloudbeat` and loops in error.

This is the code inside `elastic-agent` that handles this duplication error:
```
	for idx, inputRaw := range inputs {
		input, ok := inputRaw.(map[string]interface{})
		if !ok {
			return nil, fmt.Errorf("invalid 'inputs.%d', expected a map not a %T", idx, inputRaw)
		}
		typeRaw, ok := input[typeKey]
		if !ok {
			return nil, fmt.Errorf("invalid 'inputs.%d', 'type' missing", idx)
		}
		t, ok := typeRaw.(string)
		if !ok {
			return nil, fmt.Errorf("invalid 'inputs.%d.type', expected a string not a %T", idx, typeRaw)
		}
		if realInputType, found := aliasMapping[t]; found {
			t = realInputType
			// by replacing type we make sure component understands aliasing
			input[typeKey] = t
		}
		idRaw, ok := input[idKey]
		if !ok {
			// no ID; fallback to type
			idRaw = t
		}
		id, ok := idRaw.(string)
		if !ok {
			return nil, fmt.Errorf("invalid 'inputs.%d.id', expected a string not a %T", idx, idRaw)
		}
		if hasDuplicate(outputsMap, id) {
			return nil, fmt.Errorf("invalid 'inputs.%d.id', has a duplicate id %q. Please add a unique value for the 'id' key to each input in the agent policy", idx, id)
		}
```

Looking at the Kibana code that handles and generates these `ids` I can see the following:
```
export const storedPackagePolicyToAgentInputs = (
  packagePolicy: PackagePolicy,
  packageInfo?: PackageInfo,
  outputId: string = DEFAULT_OUTPUT.name
): FullAgentPolicyInput[] => {
  const fullInputs: FullAgentPolicyInput[] = [];

  if (!isPolicyEnabled(packagePolicy)) {
    return fullInputs;
  }

  // Marks to skip appending input information to package policy ID to make it unique if package is "limited":
  // this means that only one policy for the package can exist on the agent policy, so its ID is already unique
  const appendInputId = packageInfo && isPackageLimited(packageInfo) ? false : true;

  packagePolicy.inputs.forEach((input) => {
    if (!input.enabled) {
      return;
    }

    const inputId = appendInputId
      ? `${input.type}${input.policy_template ? `-${input.policy_template}-` : '-'}${
          packagePolicy.id
        }`
      : packagePolicy.id;
```
Notice that the code behaves differently according to this value `appendInputId` which comes from `isPackageLimited`.
Looking deeper into this method we see the following logic:
```
export const isPackageLimited = (packageInfo: PackageInfo): boolean => {
  return (packageInfo.policy_templates || []).some(
    (policyTemplate) => policyTemplate.multiple === false
  );
};
```
Notice that it checks if  `policyTemplate.multiple === false`
```
Looking at out integration manifest we can see:
```
policy_templates:
  - name: kspm
    title: KSPM
    description: Measure Kubernetes compliance with hardening guidelines
    multiple: false
```
And also:
```
  - name: cspm
    title: CSPM
    description: Measure cloud resource compliance with relevant hardening guidelines
    categories:
      - containers
      - security
      - cloud
      - aws
      - azure
      - google_cloud
    multiple: false
```

This means that this uniqueness won't be generated for us.

Other integrations do not assign `multiple: false`, which you would suspect to fail as well.
But looking at the type inside fleet we are able to see the following:
```
interface BaseTemplate {
  [RegistryPolicyTemplateKeys.name]: string;
  [RegistryPolicyTemplateKeys.title]: string;
  [RegistryPolicyTemplateKeys.description]: string;
  [RegistryPolicyTemplateKeys.icons]?: RegistryImage[];
  [RegistryPolicyTemplateKeys.screenshots]?: RegistryImage[];
  [RegistryPolicyTemplateKeys.multiple]?: boolean;
}
```
Notice that the type of `multiple` is boolean but it has a `?` which means that this is not required and will default to `undefined`.
Due to this value being `undefined` other integrations do this uniqueness even though they did not assign a `true` value which is a confusing behavior.
